# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2013 Oracle and/or its affiliates. All Rights Reserved.

top_srcdir ?= ../../../../..

include $(top_srcdir)/include/mk/env_pre.mk
CFLAGS += -pthread
include $(top_srcdir)/include/mk/generic_leaf_target.mk
